services:
  backend:
    image: pern-backend:${BUILD_NUMBER:-latest}
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    networks:
      - pern-net
    ports:
      - "5000:5000"   
      
  frontend:
    image: pern-frontend:${BUILD_NUMBER:-latest}
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    networks:
      - pern-net
    ports:
      - "5173:5173"

networks:
  pern-net:
    driver: bridge
